import { useState, useEffect } from 'react';
import { Card } from '../components/ui/card';
import { Button } from '../components/ui/button';
import { PageHeader } from '../components/PageHeader';
import { apiClient } from '../api/client';
import { FolderOpen, FileText, PenLine, Download, Copy, Check, ChevronDown, ChevronUp } from 'lucide-react';

interface DocItem {
  id: string;
  kind: 'resume' | 'cover_letter';
  title: string;
  subtitle?: string;
  createdAt: string;
  format?: 'pdf';
  downloadPath?: string;
  text?: string;
}

interface DocumentsResponse {
  resumes: DocItem[];
  coverLetters: DocItem[];
}

function formatDate(iso: string): string {
  const d = new Date(iso);
  return Number.isNaN(d.getTime())
    ? ''
    : d.toLocaleDateString(undefined, { month: 'short', day: 'numeric', year: 'numeric' });
}

export function Documents() {
  const [data, setData] = useState<DocumentsResponse>({ resumes: [], coverLetters: [] });
  const [loading, setLoading] = useState(true);
  const [openId, setOpenId] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  useEffect(() => {
    apiClient
      .get<DocumentsResponse>('/documents')
      .then((d) => setData({ resumes: d.resumes ?? [], coverLetters: d.coverLetters ?? [] }))
      .catch(() => setData({ resumes: [], coverLetters: [] }))
      .finally(() => setLoading(false));
  }, []);

  const download = (doc: DocItem) => {
    if (!doc.downloadPath) return;
    const filename = `${doc.title.replace(/[^a-zA-Z0-9]/g, '_')}.pdf`;
    apiClient.downloadBlob(doc.downloadPath, filename).catch(() => {});
  };

  const copy = async (doc: DocItem) => {
    if (!doc.text) return;
    try {
      await navigator.clipboard.writeText(doc.text);
      setCopiedId(doc.id);
      setTimeout(() => setCopiedId((c) => (c === doc.id ? null : c)), 1500);
    } catch {
      // clipboard may be blocked; no-op
    }
  };

  const total = data.resumes.length + data.coverLetters.length;

  return (
    <div className="p-6 lg:p-8 max-w-7xl mx-auto space-y-6">
      <PageHeader
        title="Documents Library"
        description="Resumes and cover letters generated by the agent"
      />

      {loading ? (
        <div className="h-40 animate-pulse rounded-2xl bg-muted/50" />
      ) : total === 0 ? (
        <Card className="border-border/60 shadow-soft">
          <div className="flex flex-col items-center justify-center text-center px-6 py-16">
            <div className="flex items-center justify-center w-14 h-14 rounded-full bg-muted mb-4">
              <FolderOpen className="w-7 h-7 text-muted-foreground" />
            </div>
            <h3 className="font-semibold text-foreground">No documents yet</h3>
            <p className="text-sm text-muted-foreground mt-1 max-w-sm">
              Tailored resumes and cover letters will appear here as the agent applies to jobs.
            </p>
          </div>
        </Card>
      ) : (
        <>
          {/* Resumes */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <FileText className="w-4 h-4 text-blue-600 dark:text-blue-400" />
              <h2 className="font-semibold text-foreground">Resumes</h2>
              <span className="text-xs text-muted-foreground">({data.resumes.length})</span>
            </div>
            {data.resumes.length === 0 ? (
              <p className="text-sm text-muted-foreground">No tailored resumes yet.</p>
            ) : (
              data.resumes.map((doc) => (
                <Card key={doc.id} className="p-4 flex items-center gap-4 border-border/60 shadow-soft card-hover">
                  <div className="flex items-center justify-center w-10 h-10 rounded-lg bg-blue-500/10 text-blue-600 dark:text-blue-400 shrink-0">
                    <FileText className="w-5 h-5" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="font-medium text-foreground truncate">{doc.title}</p>
                    <p className="text-xs text-muted-foreground mt-0.5 truncate">
                      {[doc.subtitle, formatDate(doc.createdAt)].filter(Boolean).join(' · ')}
                    </p>
                  </div>
                  {doc.downloadPath && (
                    <Button variant="outline" size="sm" className="shrink-0 gap-2" onClick={() => download(doc)}>
                      <Download className="w-4 h-4" />
                      PDF
                    </Button>
                  )}
                </Card>
              ))
            )}
          </div>

          {/* Cover letters */}
          <div className="space-y-3">
            <div className="flex items-center gap-2">
              <PenLine className="w-4 h-4 text-violet-600 dark:text-violet-400" />
              <h2 className="font-semibold text-foreground">Cover Letters</h2>
              <span className="text-xs text-muted-foreground">({data.coverLetters.length})</span>
            </div>
            {data.coverLetters.length === 0 ? (
              <p className="text-sm text-muted-foreground">No cover letters yet.</p>
            ) : (
              data.coverLetters.map((doc) => (
                <Card key={doc.id} className="border-border/60 shadow-soft">
                  <div className="p-4 flex items-center gap-4">
                    <div className="flex items-center justify-center w-10 h-10 rounded-lg bg-violet-500/10 text-violet-600 dark:text-violet-400 shrink-0">
                      <PenLine className="w-5 h-5" />
                    </div>
                    <div className="flex-1 min-w-0">
                      <p className="font-medium text-foreground truncate">{doc.title}</p>
                      <p className="text-xs text-muted-foreground mt-0.5 truncate">
                        {[doc.subtitle, formatDate(doc.createdAt)].filter(Boolean).join(' · ')}
                      </p>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <Button variant="ghost" size="sm" onClick={() => copy(doc)}>
                        {copiedId === doc.id ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
                      </Button>
                      <Button variant="ghost" size="sm" onClick={() => setOpenId((o) => (o === doc.id ? null : doc.id))}>
                        {openId === doc.id ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                      </Button>
                    </div>
                  </div>
                  {openId === doc.id && doc.text && (
                    <div className="px-4 pb-4">
                      <div className="rounded-xl border border-border/60 bg-muted/30 p-4 max-h-96 overflow-y-auto">
                        <pre className="text-sm text-foreground whitespace-pre-wrap font-sans leading-relaxed">{doc.text}</pre>
                      </div>
                    </div>
                  )}
                </Card>
              ))
            )}
          </div>
        </>
      )}
    </div>
  );
}
